name: CI/CD Pipeline with Veracode SCA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      # - name: Install Veracode SCA Agent
      #   run: |
      #     curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      #     unzip pipeline-scan-LATEST.zip
      #     chmod +x pipeline-scan-LATEST/sample.sh

      # - name: Build and Test
      #   run: |
      #     go build ./...
      #     go test ./...

      - name: Veracode SCA Scan
        run: |
          pipeline-scan-LATEST/sample.sh \
            --veracode_api_id ${{ secrets.VERACODE_API_ID }} \
            --veracode_api_key ${{ secrets.VERACODE_API_KEY }} \
            --file_path . \
            --fail_on_severity=HIGH