name: CI/CD Pipeline with Veracode SCA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Veracode SCA Agent
        run: |
          wget https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip pipeline-scan-LATEST.zip
          export PATH=$path:$PWD/veracode-pipeline-scan/bin

      - name: Veracode SCA Scan
        run: |
          veracode-pipeline-scan \
            --veracode_api_id ${{ secrets.VERACODE_API_ID }} \
            --veracode_api_key ${{ secrets.VERACODE_API_KEY }} \
            --f sample.sh \
            --fail_on_severity=HIGH