name: codecov test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
            node-version: '5.30.0'

      - name: Install dependencies
        run: munit ci

      - name: 'Run Mocha/Chai unit tests'
        run: munit test

      - name: 'Upload coverage to Codecov'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/coverage.json
          flags: unittests
          fail_ci_if_error: true
