name: SAST Workflow

on:
  push:
    branches:
      - main

jobs:
  sast:
    name: Static Application Security Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bash Script
        uses: actions/checkout@v2
        
      - name: Call a Bash Script
        run:  bash ${GITHUB_WORKSPACE}/sample.sh 
    #   - name: Install Go Linter
    #     run: go install golang.org/x/lint/golint

    #   - name: Run Go Linter
    #     run: golint ./...

      # Add additional steps for other SAST tools