#Following this structure: |-.github |--|-workflows |--|--|-secrets.yaml
name: secret pipeline

on:
    push:
        branches:
            - main
jobs:
    find_secrets_replace:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Install ShellCheck
          run: |
                sudo apt-get update
                sudo apt-get install shellcheck -y

        - name: Check secrets and replace
          run: shellcheck Secretscommand.sh  
        - name: Call a Bash Script
          run:  bash ${GITHUB_WORKSPACE}/Secretscommand.sh    
        - name: Find and Replace - Using Secrets
          run: |
            cat ./secret.properties
            echo "-------------------------------------------Changing Parameters----------------------------------------------------------------------------"
            sed -i 's/#{NAME}#/${{ secrets.NAME }}/g'  ./secret.properties
            sed -i 's|#{ID}#|${{ Secrets.ID }}|g' .//secret.properties
            echo "---------------------------------------------Parameter Changes Finished--------------------------------------------------------------------------"
            cat ./secret.properties
        
    