name: Demotest
on: [push]

jobs:
  test:
    name: Demonstrate running github-hosted shell scripts

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Call a Bash Script
      run:  bash ${GITHUB_WORKSPACE}/sample.sh 
